# Generated by Django 4.1.7 on 2023-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_notification_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/messages'),
        ),
    ]
